import re
h=open('index.html',encoding='utf-8').read()
start=h.index('<h3>8.3 Attribution accuracy')
end_marker='reaches ~0.89 without injection labels; only the trained upper bound uses them; fuel magnitude is at'
end=h.index('</div>', h.index(end_marker))+len('</div>')
p16=('<p>A real-data check on natural variation corroborates the driver half of this result without any\n'
'  injection. Among real VED trips, those whose kinematic deviation dominates carry a genuine excess of\n'
'  <b>+0.57 L/100km</b> over expectation, whereas those whose fueling-correction (trim) deviation\n'
'  dominates carry none (&minus;0.34, at the level of low-deviation trips; Mann-Whitney\n'
'  \\(p<10^{-30}\\)). Real trip excess correlates with the kinematic axis (\\(r = 0.22\\)) but not with the\n'
'  combustion axis (\\(r = 0.00\\)), and the latter stays flat even within the highest-trim quartile\n'
'  (\\(r = -0.03\\)). On real trips, then, the driver signature genuinely predicts excess fuel while the\n'
'  fueling-correction signature does not, a real-data counterpart to the silent combustion cell of\n'
'  Section 8.1; that the fleet contains no combustion-linked fuel excess is exactly why the malfunction\n'
'  signature is anchored on the controlled bench.</p>')
new=('<h3>8.3 Attribution accuracy on semi-synthetic ground truth</h3>\n'
'<p>To measure attribution we give each real VED trip a driver-caused and a fault-caused variant that\n'
'  raise fuel by the <b>same</b> amount, so fuel magnitude is uninformative, and ask a frozen attributor\n'
'  to recover the cause. Each variant perturbs only its own axis, at the feature level: the driver\n'
'  variant shifts the kinematic features along the aggressive direction learned on the external driving\n'
'  data (UAH-DriveSet, at the fleet\'s 1&nbsp;Hz rate), and the fault variant shifts the fuel trim by the\n'
'  bench\'s rich-mixture magnitude. The two effect sizes are calibrated from their sources rather than\n'
'  assumed equal: a typical aggressive window is <b>0.65</b> standard deviations on the kinematic score\n'
'  (Cohen\'s d on UAH), whereas the bench rich fault is <b>1.66</b> within-vehicle standard deviations on\n'
'  the combustion axis. Both axes are standardized to unit variance, the driver signature is the frozen\n'
'  UAH logistic, and nothing is fit to the injection labels.</p>\n'
'<p>At this realistic, asymmetric operating point the frozen source-derived attributor reaches\n'
'  <b>78.5% accuracy</b>, with a trained upper bound of 81.2%, while a classifier given only the matched\n'
'  fuel increase is at chance (<b>49.7%</b>, measured, not assumed). The result is falsifiable and passes:\n'
'  negating the frozen driver weights collapses accuracy to <b>60.0%</b> and shuffling them to 72.7%, so\n'
'  the learned signature genuinely carries the attribution rather than the injection being trivially\n'
'  recoverable (Figure 7). Accuracy rises with driver severity, from 0.79 at the realistic\n'
'  \\(d = 0.65\\) to 0.89 when the driver signal matches the fault magnitude and 0.93 for severe\n'
'  aggression. The design measures how detectable the two signatures are against real trip-to-trip noise;\n'
'  it presumes rather than proves axis-separability, which rests instead on the bench fault signature and\n'
'  the silent driver-excess cell.</p>\n'
+p16+'\n'
'<figure>\n  <img src="figures/fig6_attribution_accuracy.svg" alt="Attribution accuracy vs driver severity">\n'
'  <figcaption><b>Figure 7.</b> Attribution accuracy rises with driver aggression severity\n'
'    (Cohen\'s d on the kinematic score); at the realistic operating point (\\(d = 0.65\\)) the frozen\n'
'    source-derived attributor reaches 0.785. Negating the frozen driver weights (a falsification\n'
'    control) and using fuel magnitude alone both collapse toward chance.</figcaption>\n</figure>\n\n'
'<h3>8.4 Abstention, mixed causes, and baselines</h3>\n'
'<p>The frozen rule supports abstention: withholding a decision when the two scores are close (a margin\n'
'  \\(\\tau\\)) trades coverage for accuracy. At the realistic operating point, deciding on the 61% of\n'
'  trips with the clearest evidence raises accuracy from 78.5% to 88.3%, and on the clearest 31% to\n'
'  93.3%. In a maintenance setting an explicit "uncertain" verdict is preferable to a confident wrong\n'
'  intervention.</p>\n'
'<p>The real world does not present pure one-axis changes. Scoring dominant-cause accuracy over a grid\n'
'  of driver and fault effect sizes (Figure 8), attribution is reliable off the diagonal and falls to\n'
'  chance only where the two effects are equal and the cause is genuinely ambiguous.</p>\n'
'<figure>\n  <img src="figures/mixed_cause_grid.svg" alt="Mixed-cause dominant-cause accuracy grid">\n'
'  <figcaption><b>Figure 8.</b> Dominant-cause accuracy when both causes act, over driver severity\n'
'    \\(S_d\\) and fault effect \\(S_f\\); reliable off the diagonal, chance where they are equal.</figcaption>\n</figure>\n'
'<p>Attribution is not an artifact of one attributor. At the realistic operating point, a\n'
'  likelihood-ratio prototype against source-calibrated signature distributions matches the trained\n'
'  upper bound (0.81), the frozen argmax rule reaches 0.79, and fuel magnitude alone stays at chance\n'
'  (Table 8). The signature separation, not the choice of attributor, carries the result.</p>\n'
'<table>\n'
'  <tr><th>Attributor (realistic operating point)</th><th class="num">Accuracy</th><th>Uses injection labels?</th></tr>\n'
'  <tr><td>Fuel magnitude only</td><td class="num">0.497</td><td>n/a (chance)</td></tr>\n'
'  <tr><td>Negated driver weights (falsification)</td><td class="num">0.599</td><td>no</td></tr>\n'
'  <tr><td>Frozen source-derived argmax</td><td class="num">0.785</td><td>no</td></tr>\n'
'  <tr><td>Likelihood-ratio prototype (source-calibrated)</td><td class="num">0.812</td><td>no</td></tr>\n'
'  <tr><td>Trained upper bound</td><td class="num">0.812</td><td>yes</td></tr>\n'
'</table>\n'
'<div class="tcap"><b>Table 8.</b> Attributors at the realistic asymmetric operating point. Signature-based\n'
'  rules reach ~0.79&ndash;0.81 without injection labels; negating the frozen driver weights collapses the\n'
'  result (falsification); fuel magnitude alone is at chance.</div>')
h=h[:start]+new+h[end:]
open('index.html','w',encoding='utf-8').write(h)
print('rewrote 8.3-8.4; new block chars',len(new))
